{{- if .Values.servicename.networkPolicy.create }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ printf "%s-%s" (include "helper.fullname" .) "servicename" }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "servicename")) | nindent 4 }}
  {{- if .Values.servicename.pdb.labels }}
    {{- toYaml .Values.servicename.pdb.labels | nindent 4 }}
  {{- end }}
  {{- if .Values.servicename.pdb.annotations }}
  annotations: {{- toYaml .Values.servicename.pdb.annotations | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels: {{- include "helper.selectorLabels" (dict "root" . "componentName" "servicename") | nindent 6 }}
  policyTypes:
  {{- if (.Values.servicename.networkPolicy.ingress) }}
  - Ingress
  {{- end }}
  {{- if (.Values.servicename.networkPolicy.egress) }}
  - Egress
  {{- end }}
{{- if and (.Values.servicename.networkPolicy.ingress) (ne .Values.servicename.networkPolicy.ingress.mode "deny-all" ) }}
  ingress:
  {{- if eq .Values.servicename.networkPolicy.ingress.mode "rules" }}
  {{- range $ingress := .Values.servicename.networkPolicy.ingress.rules }}
  - from:
    {{- with $ingress.podLabel }}
    - podSelector:
        matchLabels:
        {{- toYaml . | nindent 10 }}
    {{- end }}
    {{- with $ingress.namespaceLabel }}
    - namespaceSelector:
        matchLabels:
        {{- toYaml . | nindent 10 }}
    {{- end }}
    {{- with $ingress.ipBlock }}
    - ipBlock:
        cidr: {{ .cidr }}
        {{- if (.except) }}
        except:
        {{- toYaml .except | nindent 8 }}
        {{- end }}
    {{- end }}
    {{- if ($ingress.ports) }}
    ports:
    {{- range $ports := $ingress.ports}}
    {{- if kindIs "map" $ports }}
    {{- if ($ports.protocol) }}
    - protocol: {{ $ports.protocol }}
    {{- else }}
    - protocol: TCP
    {{- end }}
      port: {{ $ports.port}}
    {{- else }}
    - protocol: TCP
      port: {{ $ports }}
    {{- end }}
    {{- end }}
    {{- end }}
  {{- end }}
  {{- else if eq .Values.servicename.networkPolicy.ingress.mode "allow-all" }}
    - {}
  {{- end }}
{{- end }}
{{- if and (.Values.servicename.networkPolicy.egress) (ne .Values.servicename.networkPolicy.egress.mode "deny-all" ) }}
  egress:
  {{- if eq .Values.servicename.networkPolicy.egress.mode "rules" }}
  {{- range $egress := .Values.servicename.networkPolicy.egress.rules }}
  - to:
    {{- with $egress.podLabel }}
    - podSelector:
        matchLabels:
        {{- toYaml . | nindent 10 }}
    {{- end }}
    {{- with $egress.namespaceLabel }}
    - namespaceSelector:
        matchLabels:
        {{- toYaml . | nindent 10 }}
    {{- end }}
    {{- with $egress.ipBlock }}
    - ipBlock:
        cidr: {{ .cidr }}
        {{- if (.except) }}
        except:
        {{- toYaml .except | nindent 10 }}
        {{- end }}
    {{- end }}
    {{- if ($egress.ports) }}
    ports:
    {{- range $ports := $egress.ports }}
    {{- if kindIs "map" $ports }}
    {{- if ($ports.protocol) }}
    - protocol: {{ $ports.protocol }}
    {{- else }}
    - protocol: TCP
    {{- end }}
      port: {{ $ports.port }}
    {{- if ($ports.endPort) }}
      {{- if lt $ports.endPort $ports.port }}
      {{- fail (printf "endPort (%d) must be >= port (%d)" $ports.endPort $ports.port) }}
      {{- else }}
      endPort: {{ $ports.endPort }}
      {{- end }}
    {{- end }}
    {{- else }}
    - protocol: TCP
      port: {{ $ports }}
    {{- end }}
    {{- end }}
    {{- end }}
  {{- end }}
  {{- else if eq .Values.servicename.networkPolicy.egress.mode "allow-all" }}
    - {}
  {{- end }}
{{- end }}
